kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: monitoring
spec:
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: app-matrix
          image: alokkusingh/app-matrix:arm64v8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: hello-service-config